[package]
name = "bpe"
version = "0.1.0"
authors = ["dmitri"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
fancy-regex = "0.4.1"
plotters = "^0.3.0"
gnuplot = "0.0.37"
unicode-segmentation = "1.3.0"
